on:
  push:
    branches:
      - main

jobs:
  build-macos:
      strategy:
        matrix:
          arch: [x86_64, aarch64]
      
      name: ${{ matrix.arch }}
      runs-on: macos-12
      steps:
        - uses: actions/checkout@v3
        - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        - name: Install crosscompiler
          run: cargo install cross
        - name: Build application
          shell: bash
          run: |
           cross build -p client-gui --release --target ${{ matrix.arch }}-apple-darwin
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.arch }}-apple-darwin
            path: target/${{ matrix.arch }}-apple-darwin/release/client-gui
