on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
      - name: Install crosscompiler
        run: cargo install cross
      - name: Build application
        shell: bash
        run: |
         cd client-gui
         cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-mac-x86
          path: target/release/client-gui
