on:
  push:
    branches:
      - main

jobs:
  build-macos:
      strategy:
        matrix:
          arch: [x86_64, aarch64]
      
      name: ${{ matrix.arch }}
      runs-on: macos-12
      steps:
        - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        - name: Add architecture ${{ matrix.arch }}
          run: rustup target add ${{ matrix.arch }}-apple-darwin
        - uses: actions/checkout@v3
        - name: Build application
          shell: bash
          run: |
           cd client-gui
           cargo build --release --target=${{ matrix.arch }}-apple-darwin
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.arch }}-apple-darwin
            path: target/${{ matrix.arch }}-apple-darwin/release/client-gui


  universal-binary:
    name: Build DMG
    needs: [build-macos]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Download x86_64
        uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: x86_64
      - name: Download arm64
        uses: actions/download-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: aarch64
      - name: Combine app bundles
        shell: bash
        run: |
          export X86_64_APPLE_DARWIN=x86_64/client-gui
          export AARCH64_APPLE_DARWIN=aarch64/client-gui
          export DMG_OUTPUT_PATH=CraftIP.dmg
          sh build/build-mac.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CraftIP.dmg
          path: CraftIP.dmg
     
