name: Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          update: true

    - name: Install dependencies
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

    - uses: actions/checkout@v1

    - name: Configure
      shell: bash
      run: ~/.cargo/bin/cargo build --bin client-gui --target=x86_64-pc-windows-msvc --release

    - name: tmp
      shell: bash
      run: find .

    - uses: actions/upload-artifact@v1
      with:
        name: client-gui.exe
        path: target\x86_64-pc-windows-msvc\release\client-gui.exe
